const NotificationType = {
  INVITE_JOIN_TIMESHARE_TO_CUSTOMER: "INVITE_JOIN_TIMESHARE_TO_CUSTOMER",
  ACCEPT_JOIN_TIMESHARE_TO_CUSTOMER: "ACCEPT_JOIN_TIMESHARE_TO_CUSTOMER",
  REJECT_JOIN_TIMESHARE_TO_CUSTOMER: "REJECT_JOIN_TIMESHARE_TO_CUSTOMER",
  NOTI_CAN_BUY_TIMESHARE_TO_CUSTOMER: "NOTI_CAN_BUY_TIMESHARE_TO_CUSTOMER ",
  NOTI_RESERVER_PLACE_TO_INVESTOR: "NOTI_RESERVER_PLACE_TO_INVESTOR",
  REQUEST_CONFIRM_BUY_TIMESHARE_TO_INVESTOR:
    "REQUEST_CONFIRM_BUY_TIMESHARE_TO_INVESTOR",
  ACCEPT_BUY_TIMESHARE_TO_CUSTOMER: "ACCEPT_BUY_TIMESHARE_TO_CUSTOMER",
  REJECT_BUY_TIMESHARE_TO_CUSTOMER: "REJECT_BUY_TIMESHARE_TO_CUSTOMER",
  REQUEST_CONFIRM_CONTRACT_TO_CUSTOMER: "REQUEST_CONFIRM_CONTRACT_TO_CUSTOMER",
  ACCEPT_CONTRACT_TO_INVESTOR: "ACCEPT_CONTRACT_TO_INVESTOR",
  CHANGE_CONTRACT_TO_CUSTOMER: "CHANGE_CONTRACT_TO_CUSTOMER",
  NOTI_PAYMENT_BY_PHASE_TO_INVESTOR: "NOTI_PAYMENT_BY_PHASE_TO_INVESTOR",
  REQUEST_HANDLE_SUPPORT_TO_ADMIN: "REQUEST_HANDLE_SUPPORT_TO_ADMIN",
  NOTI_FEEDBACK_TO_STAFF: "NOTI_FEEDBACK_TO_STAFF",
};

module.exports = NotificationType;
